# Generated by Django 3.0.8 on 2020-09-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
    ]
